clone_depth: 1

environment:
    matrix:
        - compiler: MINGW
            - platform: x64
            - platform: x86
        - compiler: MSVC
            - platform: x64
            - platform: x86
            
matrix:
    fast_finish: true
    
