clone_depth: 1

environment:
    matrix:
        - platform: MINGW
            - x64
            - x86
        - platform: MSVC
            - x64
            - x86
            
matrix:
    fast_finish: true
    
