clone_depth: 1

configuration:
    - Release
    
environment:
    matrix:
        - compiler: MINGW
        - compiler: MSVC
        
platform:
    - x64
    - x86
        
matrix:
    fast_finish: true
    
