version: 2015.1.{build}
clone_depth: 1

skip_commits:
  message: /(iiod|IIOD):.*/
    
environment:
  # Tell msys2 to add mingw64 to the path
  MSYSTEM: MINGW64
  matrix:
    - COMPILER: msvc
      GENERATOR: Visual Studio 12
    - COMPILER: mingw
      GENERATOR: Unix Makefiles

configuration:
  - Release

install:
  - echo "Checking out sub-modules..."
  - cd c:\projects
  - git clone --depth 1 https://github.com/analogdevicesinc/libiio.git
  - cd c:\projects\libiio
  - git submodule update --init
  - cd ..
  - echo "Downloading deps..."
  - cd c:\
  - appveyor DownloadFile http://swdownloads.analog.com/cse/build/libiio-win-deps.zip
  - 7z x -y "c:\libiio-win-deps.zip"
  
  #Install Inno Setup
  - choco install InnoSetup
  
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - if "%COMPILER%"=="mingw" (set OPT_PATH=C:\msys64\mingw64\bin;)
  - set PATH=%OPT_PATH%%PATH%
  - if "%COMPILER%"=="mingw" (set OPT_PATH=C:\msys64\mingw32\bin;)
  - set PATH=%OPT_PATH%%PATH%

  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu")
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "pacman -Rs --noconfirm mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-gcc-objc")
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "rm /mingw64/etc/gdbinit")
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy  mingw-w64-x86_64-gcc mingw-w64-x86_64-libusb mingw-w64-x86_64-cmake mingw-w64-x86_64-libxml2 mingw-w64-x86_64-pkg-config mingw-w64-x86_64-libzip mingw-w64-x86_64-doxygen")

  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "pacman -Rs --noconfirm mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-fortran mingw-w64-i686-gcc-libgfortran mingw-w64-i686-gcc-objc")
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "rm /mingw32/etc/gdbinit")
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy  mingw-w64-i686-gcc mingw-w64-i686-libusb mingw-w64-i686-cmake mingw-w64-i686-libxml2 mingw-w64-i686-pkg-config mingw-w64-i686-libzip mingw-w64-i686-doxygen")

build_script:
  - cd c:\projects\libiio
  - echo "Running cmake for MinGW 32 bit... "
  - mkdir build-win32
  - cd build-win32
  
  # MinGW 32 bit
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "cmake -G '%GENERATOR%' -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=/mingw32 -DCMAKE_C_COMPILER:FILEPATH=/mingw32/bin/i686-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=/mingw32/bin/i686-w64-mingw32-g++.exe -DPKG_CONFIG_EXECUTABLE:FILEPATH=/mingw32/bin/pkg-config.exe -DENABLE_IPV6:BOOL=OFF -DWITH_MATLAB_BINDINGS:BOOL=OFF -DCSHARP_BINDINGS:BOOL=OFF -DPYTHON_BINDINGS:BOOL=OFF -DLIBXML2_LIBRARIES=c/libs/32/libxml2.dll -DLIBSERIALPORT_LIBRARIES=c/libs/32/libserialport.dll.a /c/projects/libiio && make -j3")
  
  #MSVC 32 bit
  - if "%COMPILER%"=="msvc" (set MCS_EXECUTABLE_PATH="C:\Windows\Microsoft.NET\Framework\v4.0.30319")
  - if "%COMPILER%"=="msvc" (cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE:STRING="%configuration%" -DENABLE_IPV6:BOOL=OFF -DCMAKE_SYSTEM_PREFIX_PATH="C:" -DPYTHON_BINDINGS:BOOL=OFF -DLIBXML2_LIBRARIES="C:\\libs\\32\\libxml2.lib" -DLIBUSB_LIBRARIES="C:\\libs\\32\\libusb-1.0.lib" -DLIBSERIALPORT_LIBRARIES="C:\\libs\\32\\libserialport.dll.a" ..)
  - if "%COMPILER%"=="msvc" (cmake --build . --config %configuration%)
  
  - cd c:\projects\libiio
  - echo "Running cmake for 64 bit... "
  - mkdir build-win64
  - cd build-win64
  
  # MinGW 64 bit
  - if "%COMPILER%"=="mingw" (C:\msys64\usr\bin\bash -lc "cmake -G '%GENERATOR%' -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=/mingw64 -DCMAKE_C_COMPILER:FILEPATH=/mingw64/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=/mingw64/bin/x86_64-w64-mingw32-g++.exe -DPKG_CONFIG_EXECUTABLE:FILEPATH=/mingw64/bin/pkg-config.exe -DENABLE_IPV6:BOOL=OFF -DWITH_MATLAB_BINDINGS:BOOL=OFF -DCSHARP_BINDINGS:BOOL=OFF -DPYTHON_BINDINGS:BOOL=OFF -DLIBXML2_LIBRARIES=c/libs/64/libxml2.dll -DLIBSERIALPORT_LIBRARIES=c/libs/64/libserialport.dll.a /c/projects/libiio && make -j3")
  
  #MSVC 64 bit
  - if "%COMPILER%"=="msvc" (cmake -G "%GENERATOR% Win64" -DCMAKE_BUILD_TYPE:STRING="%configuration%" -DENABLE_IPV6:BOOL=OFF -DCMAKE_SYSTEM_PREFIX_PATH="C:" -DPYTHON_BINDINGS:BOOL=OFF -DLIBXML2_LIBRARIES="C:\\libs\\64\\libxml2.lib" -DLIBUSB_LIBRARIES="C:\\libs\\64\\libusb-1.0.lib" -DLIBSERIALPORT_LIBRARIES="C:\\libs\\64\\libserialport.dll.a" ..)
  - if "%COMPILER%"=="msvc" (cmake --build . --config %configuration%)
  
  - ISCC C:\projects\libiio\build-win32\libiio.iss
  - appveyor PushArtifact C:\libiio-setup.exe

